"""Single source of truth for the triage model's contract.

Feature names, physiological ranges, the target definition and the ESI label
map are imported by preprocessing, training, inference and the backend. Keeping
them here means the API, the model and the UI cannot drift apart silently.
"""

from __future__ import annotations

from pathlib import Path

# --------------------------------------------------------------------------- #
# Paths & reproducibility
# --------------------------------------------------------------------------- #

ML_ROOT = Path(__file__).resolve().parent
MODELS_DIR = ML_ROOT / "models"
DATA_DIR = ML_ROOT / "data"

RANDOM_SEED = 42

# --------------------------------------------------------------------------- #
# Target
# --------------------------------------------------------------------------- #

TARGET = "esi"
#: Emergency Severity Index acuity levels, most acute first.
ESI_CLASSES = [1, 2, 3, 4, 5]
#: Levels that must not be missed - evaluated separately (see evaluate.py).
HIGH_ACUITY_CLASSES = [1, 2]

#: Standard ESI level names (Gilboy et al., ESI Implementation Handbook).
ESI_NAMES = {
    1: "Resuscitation",
    2: "Emergent",
    3: "Urgent",
    4: "Less Urgent",
    5: "Non-Urgent",
}


def acuity_band(esi: int) -> str:
    """Coarse band used in the UI alongside the numeric ESI."""
    if esi in (1, 2):
        return "High Acuity"
    if esi == 3:
        return "Moderate Acuity"
    return "Lower Acuity"


# --------------------------------------------------------------------------- #
# Features (all available at the initial triage assessment - see features.md)
# --------------------------------------------------------------------------- #

NUMERIC_FEATURES = [
    "age",
    "heart_rate",
    "respiratory_rate",
    "systolic_bp",
    "diastolic_bp",
    "oxygen_saturation",
    "temperature",
    "pain_level",
]

CATEGORICAL_FEATURES = [
    "sex",
    "arrival_transport",
]

TEXT_FEATURE = "chief_complaint"

#: Columns derived deterministically from the raw inputs at fit and predict
#: time by :class:`ml.preprocessing.pipeline.FeatureEngineer`.
DERIVED_NUMERIC_FEATURES = [
    "shock_index",
    "pulse_pressure",
]

ALL_INPUT_FEATURES = NUMERIC_FEATURES + CATEGORICAL_FEATURES + [TEXT_FEATURE]
MODEL_NUMERIC_FEATURES = NUMERIC_FEATURES + DERIVED_NUMERIC_FEATURES

#: Core vitals - at least ``MIN_VITALS_FOR_PREDICTION`` must be present for a
#: prediction to be offered (guards against over-reliance on a near-empty form).
CORE_VITALS = [
    "heart_rate",
    "respiratory_rate",
    "systolic_bp",
    "diastolic_bp",
    "oxygen_saturation",
    "temperature",
]
MIN_VITALS_FOR_PREDICTION = 3

# --------------------------------------------------------------------------- #
# Validation domains
# --------------------------------------------------------------------------- #

#: Physiologically plausible ranges. Values outside are rejected by the API and
#: clipped to NaN during preprocessing (treated as a recording error).
FEATURE_RANGES: dict[str, tuple[float, float]] = {
    "age": (0, 120),
    "heart_rate": (10, 300),
    "respiratory_rate": (2, 80),
    "systolic_bp": (40, 300),
    "diastolic_bp": (20, 200),
    "oxygen_saturation": (50, 100),
    "temperature": (30.0, 45.0),  # degrees Celsius
    "pain_level": (0, 10),
}

SEX_VALUES = ["M", "F", "OTHER", "UNKNOWN"]
ARRIVAL_TRANSPORT_VALUES = [
    "ambulance",
    "walk_in",
    "public",
    "private",
    "helicopter",
    "police",
    "other",
    "unknown",
]

# --------------------------------------------------------------------------- #
# Clinical boundary - shown wherever a prediction is surfaced
# --------------------------------------------------------------------------- #

CLINICAL_NOTICE = (
    "This prediction is generated by a machine-learning model and is intended "
    "only as clinical decision support. It does not constitute a diagnosis or "
    "replace professional clinical judgement. Final triage requires human review."
)
