"use client";

import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import {
  countVitals,
  esiTone,
  getTriageHealth,
  MIN_VITALS,
  predictTriage,
  saveTriage,
  type TriageFeatures,
  type TriageHealth,
  type TriagePrediction,
} from "@/lib/triage";

const EMPTY: TriageFeatures = {
  age: 50,
  sex: "M",
  arrival_transport: "ambulance",
  chief_complaint: "",
  heart_rate: undefined,
  respiratory_rate: undefined,
  systolic_bp: undefined,
  diastolic_bp: undefined,
  oxygen_saturation: undefined,
  temperature: undefined,
  pain_level: undefined,
};

const TRANSPORTS = ["ambulance", "walk_in", "public", "private", "helicopter", "police", "other"];

export default function TriagePage() {
  const { user, loading, getAccessToken } = useAuth();
  const router = useRouter();

  const [f, setF] = useState<TriageFeatures>(EMPTY);
  const [health, setHealth] = useState<TriageHealth | null>(null);
  const [pred, setPred] = useState<TriagePrediction | null>(null);
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState<string | null>(null);

  // Human review state
  const [overriding, setOverriding] = useState(false);
  const [finalEsi, setFinalEsi] = useState<number>(3);
  const [reason, setReason] = useState("");
  const [outcome, setOutcome] = useState<{ final: number; overridden: boolean } | null>(null);

  useEffect(() => {
    if (!loading && !user) router.replace("/login");
  }, [loading, user, router]);

  useEffect(() => {
    if (!user) return;
    getTriageHealth(getAccessToken())
      .then(setHealth)
      .catch(() => setHealth(null));
  }, [user, getAccessToken]);

  const nVitals = useMemo(() => countVitals(f), [f]);
  const canPredict = f.chief_complaint.trim().length > 0 && nVitals >= MIN_VITALS;

  function num(name: keyof TriageFeatures) {
    return (e: React.ChangeEvent<HTMLInputElement>) => {
      const v = e.target.value;
      setF((p) => ({ ...p, [name]: v === "" ? undefined : Number(v) }));
    };
  }

  function resetPrediction() {
    setPred(null);
    setOutcome(null);
    setOverriding(false);
    setReason("");
  }

  async function runPredict(e: React.FormEvent) {
    e.preventDefault();
    setMsg(null);
    resetPrediction();
    setBusy(true);
    try {
      const p = await predictTriage(f, getAccessToken());
      setPred(p);
      setFinalEsi(p.prediction.esi);
    } catch (err) {
      setMsg((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  async function accept() {
    await persist(pred!.prediction.esi, null);
  }

  async function submitOverride() {
    if (!reason.trim()) {
      setMsg("A brief clinical reason is required to override the model.");
      return;
    }
    await persist(finalEsi, reason.trim());
  }

  async function persist(final: number, overrideReason: string | null) {
    setBusy(true);
    setMsg(null);
    try {
      const res = await saveTriage(
        { features: f, human_final_esi: final, override_reason: overrideReason },
        getAccessToken(),
      );
      setOutcome({
        final: res.record.human_final_esi ?? final,
        overridden: res.record.was_overridden,
      });
    } catch (err) {
      setMsg((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  if (loading || !user) {
    return <div className="py-24 text-center text-[var(--cc-muted)]">Loading…</div>;
  }

  const disabled = health && (health.status === "disabled" || health.enabled === false);

  return (
    <div className="flex flex-col gap-10">
      <div>
        <h1 className="text-3xl font-bold md:text-4xl">Emergency triage support</h1>
        <p className="mt-2 max-w-2xl text-lg text-[var(--cc-muted)]">
          Enter the initial assessment. A machine-learning model suggests an ESI acuity
          (1–5) as <strong>decision support</strong>. The clinician always makes the final
          triage decision.
        </p>
      </div>

      <p className="rounded-xl border border-[var(--cc-border)] bg-[var(--cc-surface-2)] px-4 py-3 text-sm text-[var(--cc-muted)]">
        This prediction is generated by a machine-learning model and is intended only as
        clinical decision support. It does not constitute a diagnosis or replace
        professional clinical judgement.
      </p>

      {disabled && (
        <p className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-amber-100">
          ML triage support is currently disabled. Continue with standard manual triage.
        </p>
      )}

      {msg && (
        <p className="rounded-xl bg-red-500/10 px-4 py-3 text-red-200" role="alert">
          {msg}
        </p>
      )}

      <form
        onSubmit={runPredict}
        className="rounded-2xl border border-[var(--cc-border)] bg-[var(--cc-surface)] p-6 sm:p-8"
      >
        <h2 className="text-xl font-semibold text-[var(--cc-accent)]">Initial assessment</h2>

        <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          <Field label="Age (years)">
            <input type="number" min={0} max={120} value={f.age}
              onChange={num("age")} className={inputCls} />
          </Field>
          <Field label="Sex">
            <select value={f.sex} onChange={(e) => setF((p) => ({ ...p, sex: e.target.value }))}
              className={inputCls}>
              <option value="M">Male</option>
              <option value="F">Female</option>
              <option value="OTHER">Other</option>
              <option value="UNKNOWN">Unknown</option>
            </select>
          </Field>
          <Field label="Arrival transport">
            <select value={f.arrival_transport}
              onChange={(e) => setF((p) => ({ ...p, arrival_transport: e.target.value }))}
              className={inputCls}>
              {TRANSPORTS.map((t) => (
                <option key={t} value={t}>{t.replace("_", " ")}</option>
              ))}
            </select>
          </Field>

          <Field label="Heart rate (bpm)">
            <input type="number" value={f.heart_rate ?? ""} onChange={num("heart_rate")} className={inputCls} />
          </Field>
          <Field label="Respiratory rate (/min)">
            <input type="number" value={f.respiratory_rate ?? ""} onChange={num("respiratory_rate")} className={inputCls} />
          </Field>
          <Field label="Oxygen saturation (%)">
            <input type="number" value={f.oxygen_saturation ?? ""} onChange={num("oxygen_saturation")} className={inputCls} />
          </Field>
          <Field label="Systolic BP (mmHg)">
            <input type="number" value={f.systolic_bp ?? ""} onChange={num("systolic_bp")} className={inputCls} />
          </Field>
          <Field label="Diastolic BP (mmHg)">
            <input type="number" value={f.diastolic_bp ?? ""} onChange={num("diastolic_bp")} className={inputCls} />
          </Field>
          <Field label="Temperature (°C)">
            <input type="number" step="0.1" value={f.temperature ?? ""} onChange={num("temperature")} className={inputCls} />
          </Field>
          <Field label="Pain level (0–10)">
            <input type="number" min={0} max={10} value={f.pain_level ?? ""} onChange={num("pain_level")} className={inputCls} />
          </Field>
        </div>

        <Field label="Chief complaint" className="mt-5">
          <textarea
            value={f.chief_complaint}
            onChange={(e) => setF((p) => ({ ...p, chief_complaint: e.target.value }))}
            placeholder="e.g. central chest pain radiating to left arm, sweaty"
            className="focus-ring min-h-[80px] w-full rounded-xl border border-[var(--cc-border)] bg-[var(--cc-bg)] px-4 py-3 text-lg"
          />
        </Field>

        <p className="mt-3 text-sm text-[var(--cc-muted)]">
          {nVitals} of 6 vital signs entered — at least {MIN_VITALS} are required.
        </p>

        <button
          type="submit"
          disabled={busy || !canPredict || !!disabled}
          className="focus-ring mt-5 min-h-[52px] w-full rounded-xl bg-[var(--cc-accent)] text-lg font-semibold text-zinc-950 disabled:opacity-50 sm:w-auto sm:px-10"
        >
          {busy ? "Predicting…" : "Predict triage"}
        </button>
      </form>

      {pred && (
        <section
          className={`rounded-2xl border-2 p-6 sm:p-8 ${esiTone(pred.prediction.esi)}`}
          aria-label="Model triage prediction"
        >
          <p className="text-xs font-bold uppercase tracking-widest opacity-80">
            Model prediction · decision support only
          </p>

          <div className="mt-3 flex flex-wrap items-baseline gap-x-4 gap-y-1">
            <span className="text-5xl font-black tabular-nums">ESI {pred.prediction.esi}</span>
            <span className="text-2xl font-bold">{pred.prediction.label}</span>
            <span className="text-lg opacity-80">({pred.prediction.esi_name})</span>
          </div>

          <p className="mt-2 text-sm opacity-90">
            Model confidence {Math.round(pred.confidence * 100)}% · {pred.model.name}{" "}
            {pred.model.version}
            {pred.model.type === "heuristic" && " · rule-based fallback (not ML)"}
          </p>

          <div className="mt-4">
            <p className="text-sm font-semibold">Probability by level</p>
            <div className="mt-2 flex flex-col gap-1">
              {Object.entries(pred.probabilities).map(([esi, p]) => (
                <div key={esi} className="flex items-center gap-2 text-sm">
                  <span className="w-12 tabular-nums">ESI {esi}</span>
                  <span className="h-2 flex-1 overflow-hidden rounded bg-black/20">
                    <span className="block h-full bg-current" style={{ width: `${p * 100}%` }} />
                  </span>
                  <span className="w-12 text-right tabular-nums">{Math.round(p * 100)}%</span>
                </div>
              ))}
            </div>
          </div>

          {pred.explanation.top_features.length > 0 && (
            <div className="mt-4">
              <p className="text-sm font-semibold">Why? (model drivers, not a clinical assessment)</p>
              <ul className="mt-2 flex flex-col gap-1 text-sm">
                {pred.explanation.top_features.map((c) => (
                  <li key={c.feature} className="flex items-center justify-between gap-3">
                    <span>
                      {c.label ?? c.feature.replace(/_/g, " ")}
                      <span className="ml-2 opacity-70">
                        {c.impact === "increased_acuity"
                          ? "↑ toward higher acuity"
                          : c.impact === "decreased_acuity"
                            ? "↓ toward lower acuity"
                            : "neutral"}
                      </span>
                    </span>
                    <span className="tabular-nums opacity-70">
                      {Math.round(c.importance * 100)}%
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          <p className="mt-5 rounded-lg bg-black/20 px-4 py-3 text-sm font-semibold">
            ⚠ Human review required — the model does not set the triage level.
          </p>

          {!outcome && (
            <div className="mt-5 flex flex-wrap gap-3">
              <button type="button" onClick={accept} disabled={busy}
                className="focus-ring min-h-[48px] rounded-xl bg-white/15 px-6 font-semibold hover:bg-white/25">
                Accept ESI {pred.prediction.esi}
              </button>
              <button type="button" onClick={() => setOverriding((v) => !v)} disabled={busy}
                className="focus-ring min-h-[48px] rounded-xl border border-current px-6 font-semibold">
                Override
              </button>
            </div>
          )}

          {overriding && !outcome && (
            <div className="mt-4 rounded-xl border border-current/40 bg-black/10 p-4">
              <div className="flex flex-wrap items-end gap-4">
                <label className="flex flex-col gap-1 text-sm font-medium">
                  Final clinical ESI
                  <select value={finalEsi} onChange={(e) => setFinalEsi(Number(e.target.value))}
                    className="focus-ring min-h-[44px] rounded-lg border border-[var(--cc-border)] bg-[var(--cc-bg)] px-3 text-[var(--cc-text)]">
                    {[1, 2, 3, 4, 5].map((n) => (
                      <option key={n} value={n}>ESI {n}</option>
                    ))}
                  </select>
                </label>
              </div>
              <label className="mt-3 flex flex-col gap-1 text-sm font-medium">
                Reason for overriding the model
                <textarea value={reason} onChange={(e) => setReason(e.target.value)}
                  placeholder="Clinical rationale for a different triage level"
                  className="focus-ring min-h-[70px] rounded-lg border border-[var(--cc-border)] bg-[var(--cc-bg)] px-3 py-2 text-[var(--cc-text)]" />
              </label>
              <button type="button" onClick={submitOverride} disabled={busy}
                className="focus-ring mt-3 min-h-[44px] rounded-lg bg-white/15 px-5 font-semibold hover:bg-white/25">
                Save final triage
              </button>
            </div>
          )}
        </section>
      )}

      {outcome && (
        <section className="rounded-2xl border-2 border-[var(--cc-accent)] bg-[var(--cc-surface)] p-6 sm:p-8">
          <p className="text-xs font-bold uppercase tracking-widest text-[var(--cc-accent)]">
            Final clinical triage — recorded
          </p>
          <p className="mt-2 text-4xl font-black tabular-nums">ESI {outcome.final}</p>
          <p className="mt-2 text-[var(--cc-muted)]">
            {outcome.overridden
              ? `Clinician overrode the model prediction of ESI ${pred?.prediction.esi}. Both values are stored.`
              : `Clinician accepted the model prediction of ESI ${pred?.prediction.esi}. Both values are stored.`}
          </p>
          <button type="button" onClick={() => { setF(EMPTY); resetPrediction(); }}
            className="focus-ring mt-5 min-h-[48px] rounded-xl border border-[var(--cc-border)] px-6 font-medium hover:border-[var(--cc-accent)]">
            New assessment
          </button>
        </section>
      )}
    </div>
  );
}

const inputCls =
  "focus-ring min-h-[48px] w-full rounded-xl border border-[var(--cc-border)] bg-[var(--cc-bg)] px-4 text-lg";

function Field({
  label,
  children,
  className = "",
}: {
  label: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <label className={`flex flex-col gap-1.5 ${className}`}>
      <span className="text-sm font-medium text-[var(--cc-muted)]">{label}</span>
      {children}
    </label>
  );
}
